### ISSUE TITLE
Fix cluster icon colors

### ISSUE THREAD

**Issue by heyyeyheman** [nationalparkservice/npmap-species#11]
When using multiple species observation sets, the most recently used color overwrites the color of all species icons (only clusters, individual markers are fine).

**Comment by jduggan1** [comment]
Temporary solution is to not use cluster icons. I'm leaving this open until such time as cluster icons can be integrated.

**Comment by tpcolson** [comment]
John, can you provide a more detailed explanation on the cause of this one
for Nate? I'd like to stick with the clustering functionality within the
npmap api if at possible.  If necessary start a new ticket at a more
technical level that Nate can share with cartodb  team....



On Oct 7, 2015, at 9:42 PM, John Duggan <notifications@github.com> wrote:

Temporary solution is to not use cluster icons. I'm leaving this open until
such time as cluster icons can be integrated.

—
Reply to this email directly or view it on GitHub
<https://github.com/nationalparkservice/npmap-species/issues/11#issuecomment-146390290>
.

**Comment by nateirwin** [comment]
Take a look at the source for this example: http://www.nps.gov/lib/npmap.js/2.0.1/examples/geojson-layer-clustered.html. You can change the cluster color like this:

    cluster: {
      clusterIcon: '#000'
    }

**Comment by jduggan1** [comment]
Nate, in our particular case, we are trying to show three different sets of cluster icons, each with a distinct color. When trying to do this earlier, I ran into a problem with the color of the last set added to the map overwriting the color of the first two sets added.

I think the reason this happens is because the specified color is applied to a class which all three of the sets of cluster icons share.

Is this something I am able to overcome with the API?

**Comment by nateirwin** [comment]
Try this:

    cluster: {
      clusterIcon: {
        small: {
          color: '#000'
        },
        medium: {
          color: '#111'
        },
        large: {
          color: '#222'
        }
      }
    }

**Comment by jduggan1** [comment]
Nate, sorry for the delay, but this isn't exactly what I have in mind. I need three separate species to each have cluster icons of unique color (within each species, the small/medium/large icons should be the same color). Since the colors are applied to the cluster icons' class specifying them as small/medium/large, the last species added overwrites the color for the first two.

If it isn't already supported, I think you would need to add a class/id/etc. to uniquely identify each cluster icon set, and apply the color to that class instead.

**Comment by nateirwin** [comment]
Ah gotcha. I've opened a new ticket for this in the NPMap.js repository. This is definitely unexpected behavior: https://github.com/nationalparkservice/npmap.js/issues/239.
