### ISSUE TITLE
Show observations persists when it shouldn't

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#47]
When comparing species 1 distro to species 2 and 3, AND enabling show observations, the geojsons persist when another search function is selected, e.g. selecting similar enviro. When activating another search function, geojsons (except for species 1) should be removed. This gets further confusing, when, in the search enviro function, a NEW species 1 and 2 are selected for comparison, the previous geojsons still persist.

**Comment by jduggan1** [comment]
Just to make sure, are you sure that those geojsons aren't being removed? The colors will change for all geojson markers (including those already displayed) when a species is added due to a separate bug, so it may appear that they are persisting even if they aren't.

If they are indeed staying, I am having difficulty reproducing this (screenshots would be helpful). :-)

**Comment by jduggan1** [comment]
This issue is gone with the updated site.
