### ISSUE TITLE
Popped In Map

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#57]
When I pop the map back into the home page/landing page, it looks strange because it does not resize to fit the small window. Not sure if this issue has been address in another issue. You can see from the image below that the size and extent of the map looks odd and unusable. I know that the size is an extreme limitation, but we may want to do some basic resizing or reformatting to make it a bit less awkward looking. Being that the map is still functional when popped in, it needs to also actually be usable, if that makes sense. 

![5](https://cloud.githubusercontent.com/assets/8036575/8546565/dd98f278-2486-11e5-96bd-97bef5e30f9d.PNG)

**Comment by jduggan1** [comment]
Unfortunately, there is not a lot I can do about this.  There simply isn't enough space to fit the controls we want to have, and it sounded last time like it wasn't an option to disable the control when not in fullscreen mode.

I'll add the user experience label so that Sarah can take a look at this.

**Comment by jduggan1** [comment]
This issue is gone with the updated site.
