### ISSUE TITLE
NPS title bar appears in fullscreen

### ISSUE THREAD

**Issue by jduggan1** [nationalparkservice/npmap-species#60]
The title bar from the landing page shows up in fullscreen mode.

![image](https://cloud.githubusercontent.com/assets/8481770/9229704/69ada5d4-40ec-11e5-87b3-1b95f2f1a008.png)

@tpcolson: I was able to reproduce this.  I have a couple of questions still to help determine what's happening:

1. Does this happen every time you load the page?
2. Does exiting and re-entering fullscreen mode resolve the problem?

**Comment by tpcolson** [comment]
Yes, everytime. even after reboot and cache clear. @nateirwin could this be related to whatever was fixed yesterday? Is this a NPMap API thing?

**Comment by nateirwin** [comment]
This is because of the old NPS design that the page is using. We used to have to tweak the z-index of the header element programatically when a map entered and exited fullscreen to hide the header. So there are two fixes:

1. Migrate up to the new NPS.gov design that uses nps-bootstrap (https://github.com/nationalparkservice/bootstrap)
2. Hook into the ‘enterfullscreen’ and ‘exitfullscreen’ events and set the z-index of the header element.
Let me know if you all need any code samples, etc.

**Comment by jduggan1** [comment]
The 2nd fix is already implemented.  Could this bug be caused by the fullscreen button being hit before the header element is loaded (thus the z-index change doesn't actually do anything)?

With that said, we should probably just migrate to using nps-bootstrap anyways.

**Comment by jduggan1** [comment]
@tpcolson: Is there any reason I cannot update our site to make use of new design?

**Comment by tpcolson** [comment]
Do it

**Comment by jduggan1** [comment]
This is a bug from the old design that isn't possible with the new one. Not sure why I left it open.
