### ISSUE TITLE
Basemaps should be correctly named

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#77]
Basemaps should be correctly named, e.g "NPS Park Tiles" "Map Box Terrain" "ESRI Topographic"

Basemaps should be correctly named
![image](https://cloud.githubusercontent.com/assets/5861784/10481886/f6186b04-7241-11e5-80e1-fd6925ab1422.png)

**Comment by huang-utk** [comment]
When we tested this with early users on campus, some of them commented not knowing what are “NPS Park Tiles”, “Map Box Terrain” and “ESRI Topographic”. We changed the map names due to that concern. If the intended audience should know what those maps are, we can change back to using the official names. -Jian

**Comment by jduggan1** [comment]
I went ahead and reverted to the original, correct names. This is trivial to change, so we can discuss this further during next week's meeting if you want to.
