### ISSUE TITLE
Move tooltips text 

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#94]
Related to https://github.com/nationalparkservice/npmap-species/issues/93, since the "top" is restricted space and needs to follow the NPMap Builder template, move the "Tooltips on ? -" text down so it's on top of the "Draw on Map" box.

**Comment by jduggan1** [comment]
I don't think I can pull that part of the banner down into the map controls section due to a lack of space. That said, with the way I've set things up these buttons are below that restricted space (I basically just moved my entire tool immediately below that header), so I don't think this should be an issue.
