### ISSUE TITLE
Truncates on 17 inch monitor

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#98]
Truncates on 17 inch monitor

![image](https://cloud.githubusercontent.com/assets/5861784/12731047/c887b5f2-c8fc-11e5-86bf-0573dea950c2.png)

**Comment by jduggan1** [comment]
Rather than the size, the resolution of the monitor determines if this will happen or not. I'm guessing from looking at this that it's a 1280x1024 display, which has less than the 1366 pixel width in which we can fit the tools. Monitors less than 1366 pixels wide are rare outside of mobile devices (as a point of reference, our site currently experiences less than 10% of it's traffic on monitors of this size).

Because of this, I think anyone who has such a monitor is going to have to live with scrolling a bit to access the right-most portion of the tool. Alternatively, the user can zoom out in most browsers which would allow the full tool to be visible without scrolling.
